name: Matrix Multiplication CI/CD Pipeline

on: 
  [push]


jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirement.txt

      - name: Lint with flake8
        run: |
          flake8 *.py --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501

  build-code:
    name: Build Code
    runs-on: ubuntu-latest
    needs: lint-code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build (Execute Python Script)
        run: python matrix_operations.py

  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build-code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt

      - name: Execute Unit Tests
        run: python matrix_test.py
